# Generated by Django 5.2.3 on 2025-10-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrecord',
            name='sold_by',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
