# Generated by Django 5.2.3 on 2025-10-22 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_profile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
    ]
