# Generated by Django 5.2.3 on 2025-10-22 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_profile_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
